# To boot the app run the following:
# docker-compose run auto-gpt
# NOTE: Version 3.9 requires at least docker-compose version 1.29.0 !
version: "3.9"

services:
  auto-gpt:
    build: ./
    env_file:
      - .env
    ports:
      - "8765:8765"
      SUNCO_APP_ID: ${SUNCO_APP_ID}
      SUNCO_API_KEY: ${SUNCO_API_KEY}
      SUNCO_API_SECRET: ${SUNCO_API_SECRET}
      ZENDESK_API_TOKEN: ${ZENDESK_API_TOKEN}
      ZENDESK_SUBDOMAIN: ${ZENDESK_SUBDOMAIN}
      ZENDESK_EMAIL: ${ZENDESK_EMAIL}
      AUTO_GPT_WEBSOCKET_SERVER_HOST: ${AUTO_GPT_WEBSOCKET_SERVER_HOST:-0.0.0.0}
      AUTO_GPT_WEBSOCKET_SERVER_PORT: ${AUTO_GPT_WEBSOCKET_SERVER_PORT:-8765}
    volumes:
      - ./:/app
    profiles: ["exclude-from-up"]
